version: "2"

services:
  was:
    image: registry.sangah.com/stnd-pmis
    volumes:
    - app:/usr/local/webapp
    - tmp:/tmp
    environment: 
    - DB_URL
    - DB_PASSWORD
    - DB_USERNAME

  nginx:
    build: nginx
    #image: sangah/pmis-nginx
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - app:/var/www
    - $SSL_CERT:/usr/share/nginx/ssl/nginx.crt
    - $SSL_KEY:/usr/share/nginx/ssl/nginx.key
    environment: 
    - SSL_ENABLED
    
volumes:
  app:
  tmp:
  ngx: